const FLAG_BY_TEAM: Record<string, string> = {
  日本: "🇯🇵",
  Japan: "🇯🇵",
  ブラジル: "🇧🇷",
  Brazil: "🇧🇷",
  アルゼンチン: "🇦🇷",
  Argentina: "🇦🇷",
  フランス: "🇫🇷",
  France: "🇫🇷",
  スペイン: "🇪🇸",
  Spain: "🇪🇸",
  ドイツ: "🇩🇪",
  Germany: "🇩🇪",
  イングランド: "🏴",
  England: "🏴",
  オランダ: "🇳🇱",
  Netherlands: "🇳🇱",
  ポルトガル: "🇵🇹",
  Portugal: "🇵🇹",
  イタリア: "🇮🇹",
  Italy: "🇮🇹",
  クロアチア: "🇭🇷",
  Croatia: "🇭🇷",
  ベルギー: "🇧🇪",
  Belgium: "🇧🇪",
  ウルグアイ: "🇺🇾",
  Uruguay: "🇺🇾",
  メキシコ: "🇲🇽",
  Mexico: "🇲🇽",
  アメリカ: "🇺🇸",
  米国: "🇺🇸",
  USA: "🇺🇸",
  "United States": "🇺🇸",
  カナダ: "🇨🇦",
  Canada: "🇨🇦",
  モロッコ: "🇲🇦",
  Morocco: "🇲🇦",
  韓国: "🇰🇷",
  "South Korea": "🇰🇷",
  オーストラリア: "🇦🇺",
  Australia: "🇦🇺",
  スイス: "🇨🇭",
  Switzerland: "🇨🇭",
  デンマーク: "🇩🇰",
  Denmark: "🇩🇰",
  セルビア: "🇷🇸",
  Serbia: "🇷🇸",
  ポーランド: "🇵🇱",
  Poland: "🇵🇱",
  セネガル: "🇸🇳",
  Senegal: "🇸🇳",
  ガーナ: "🇬🇭",
  Ghana: "🇬🇭",
  カメルーン: "🇨🇲",
  Cameroon: "🇨🇲",
  エクアドル: "🇪🇨",
  Ecuador: "🇪🇨",
  コスタリカ: "🇨🇷",
  "Costa Rica": "🇨🇷",
  サウジアラビア: "🇸🇦",
  "Saudi Arabia": "🇸🇦",
  イラン: "🇮🇷",
  Iran: "🇮🇷",
  カタール: "🇶🇦",
  Qatar: "🇶🇦",
  ウェールズ: "🏴",
  Wales: "🏴",
};

export function teamFlag(team?: string | null): string {
  if (!team) return "🏳️";
  return FLAG_BY_TEAM[team] ?? "🏳️";
}
