/** English → Japanese names for 2026 World Cup nations. Falls back to the original. */
const JA_TEAM: Record<string, string> = {
  Algeria: "アルジェリア",
  Argentina: "アルゼンチン",
  Australia: "オーストラリア",
  Austria: "オーストリア",
  Belgium: "ベルギー",
  "Bosnia & Herzegovina": "ボスニア・ヘルツェゴビナ",
  Brazil: "ブラジル",
  Canada: "カナダ",
  "Cape Verde": "カーボベルデ",
  Colombia: "コロンビア",
  Croatia: "クロアチア",
  "Curaçao": "キュラソー",
  "Czech Republic": "チェコ",
  "DR Congo": "コンゴ民主共和国",
  Ecuador: "エクアドル",
  Egypt: "エジプト",
  England: "イングランド",
  France: "フランス",
  Germany: "ドイツ",
  Ghana: "ガーナ",
  Haiti: "ハイチ",
  Iran: "イラン",
  Iraq: "イラク",
  "Ivory Coast": "コートジボワール",
  Japan: "日本",
  Jordan: "ヨルダン",
  Mexico: "メキシコ",
  Morocco: "モロッコ",
  Netherlands: "オランダ",
  "New Zealand": "ニュージーランド",
  Norway: "ノルウェー",
  Panama: "パナマ",
  Paraguay: "パラグアイ",
  Portugal: "ポルトガル",
  Qatar: "カタール",
  "Saudi Arabia": "サウジアラビア",
  Scotland: "スコットランド",
  Senegal: "セネガル",
  "South Africa": "南アフリカ",
  "South Korea": "韓国",
  Spain: "スペイン",
  Sweden: "スウェーデン",
  Switzerland: "スイス",
  Tunisia: "チュニジア",
  Turkey: "トルコ",
  USA: "アメリカ",
  Uruguay: "ウルグアイ",
  Uzbekistan: "ウズベキスタン",
};

export function jaTeam(name: string): string {
  return JA_TEAM[name] ?? name;
}
